[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "as3lib-miniAMF"
version = "1.0"
authors = [{name = "ajdelguidice", email = "ajdelguidice@gmail.com"}]
description = "A fork of Mini-AMF using up to date dependencies."
readme = {file = "README.md", content-type = "text/markdown"}
license = "MIT"
license-files = ["LICENSE"]
keywords = ["amf", "amf0", "amf3", "actionscript", "air", "flash", "flashplayer", "bytearray", "recordset", "decoder", "encoder", "sharedobject", "lso", "sol"]
classifiers = [
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.7",
    "Topic :: Utilities"
]
requires-python = ">=3.7"
dependencies = [
    "setuptools",
    "difusedxml"
]
packages=["miniamf", "miniamf._accel", "miniamf.adapters", "miniamf.util"]

[project.urls]
Homepage = "https://github.com/ajdelguidice/as3lib-miniAMF"

[pyproject.optional-dependencies]
docs = ["sphinx >= 1.5"]
